/* ============================================================
   Restaurant OS — precompute the MODEL
   Building the model from scratch walks ~7,400 unit-days of PMIX and takes
   seconds. That is fine in Node, unacceptable on page load. This bakes the
   period-grain aggregates to a static script the browser reads instantly.

   Transaction-level detail (day PMIX, punches, invoice lines) is NOT baked —
   it stays lazily computable in the browser from the same seeds, so every
   drill-down still resolves without shipping a 100 MB payload.

   Run after any change to the engine:  npm run build
   ============================================================ */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FILES = [
  'rand.js', 'data-calendar.js', 'data-company.js', 'data-menu.js',
  'engine-sales.js', 'engine-labor.js', 'engine-cogs.js', 'engine-finance.js', 'model.js'
];

const ctx = vm.createContext({ console });
for (const f of FILES) {
  vm.runInContext(fs.readFileSync(path.join(ROOT, 'js', f), 'utf8'), ctx, { filename: f });
}

const t0 = Date.now();
const payload = vm.runInContext(`(function () {
  var M = RG.model();
  /* period PMIX per unit is what the menu page reads — bake it too */
  M.pmix = {};
  M.periods.slice(-13).forEach(function (p) {
    M.pmix[p] = {};
    RG.UNITS.forEach(function (u) { M.pmix[p][u.id] = RG.periodPmix(u.id, p); });
  });
  /* daily series for the trailing 13 periods drives every trend chart */
  M.daily = {};
  RG.UNITS.forEach(function (u) { M.daily[u.id] = []; });
  M.periods.slice(-13).forEach(function (pk) {
    RG.CAL.daysIn(pk).forEach(function (d) {
      RG.UNITS.forEach(function (u) {
        var s = RG.daySales(u.id, d.iso);
        var L = RG.dayLabor(u.id, d.iso);
        M.daily[u.id].push({
          iso: d.iso, p: pk, dow: d.dow, closed: !!s.closed,
          net: s.net, gross: s.gross, covers: s.covers, checks: s.checks,
          disc: s.discounts, comps: s.comps, voids: s.voids,
          ch: s.byChannel, dp: s.byDaypart,
          hrs: L.hours, labor: L.cost, ot: L.otHours,
          wx: s.weather ? s.weather.label : null,
          hol: s.holiday ? s.holiday.name : null
        });
      });
    });
  });
  /* Money is already stored at 2dp; ratios carry full float precision and
     account for most of the payload. 5dp is far finer than anything the UI
     renders, and it cuts the file by roughly a third. */
  return JSON.stringify(M, function (k, v) {
    return (typeof v === 'number' && !Number.isInteger(v))
      ? Math.round(v * 1e5) / 1e5 : v;
  });
})()`, ctx, { filename: 'build-payload' });
const ms = Date.now() - t0;

/* Split the payload so first paint only pays for the core.
   Every page loads model-precomputed.js; only trend pages load the daily
   series, and only the menu page loads PMIX. */
const M = JSON.parse(payload);
const daily = M.daily, pmix = M.pmix;
delete M.daily; delete M.pmix;

function emit(file, varName, obj, note) {
  const body = JSON.stringify(obj);
  fs.writeFileSync(path.join(ROOT, 'js', file),
    `/* GENERATED by scripts/build-model.mjs — do not edit by hand.\n   ${note}\n   Rebuild with: npm run build */\n` +
    `(function(g){var RG=g.RG||(g.RG={});RG.${varName}=${body};})` +
    `(typeof window!=="undefined"?window:globalThis);\n`);
  return (fs.statSync(path.join(ROOT, 'js', file)).size / 1024).toFixed(0);
}

const a = emit('model-precomputed.js', 'PRECOMPUTED', M,
  `Period-grain P&L, scorecard, KPIs, bridges and triage for ${M.units.length} units. Loaded by every page.`);
const b = emit('model-daily.js', 'DAILY', daily,
  'Daily sales/labor series for the trailing 13 periods. Loaded only by trend pages.');
const c = emit('model-pmix.js', 'PMIX', pmix,
  'Period PMIX by unit. Loaded only by the menu-engineering page.');

console.log(`\n  Precomputed MODEL written:`);
console.log(`    model-precomputed.js  ${a} KB   core — every page`);
console.log(`    model-daily.js        ${b} KB   trend pages only`);
console.log(`    model-pmix.js         ${c} KB   menu page only`);
console.log(`  ${M.units.length} units x ${M.periods.length} periods · built in ${ms} ms`);
console.log(`  Current period ${M.kpi.label}  net sales $${Math.round(M.kpi.netSales).toLocaleString()}\n`);
